"""Remove SMS API token setting and switch to SQLite

Revision ID: be428a7c7f7e
Revises: e9a32d72b149
Create Date: 2025-08-10 10:27:47.616573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be428a7c7f7e'
down_revision: Union[str, Sequence[str], None] = 'e9a32d72b149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
